# Generated by Django 6.1 on 2026-08-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL de la imagen del curso', null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
