# Generated by Django 6.1 on 2026-08-17 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0002_curso_imagen_url_alter_curso_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregunta',
            options={'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='enunciado',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='examen',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='capacitaciones.curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta',
            name='texto',
            field=models.TextField(default=1, verbose_name='Texto de la pregunta'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='Texto de la opción')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='¿Es la opción correcta?')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='capacitaciones.pregunta')),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
            },
        ),
        migrations.CreateModel(
            name='ResultadoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.FloatField(verbose_name='Porcentaje obtenido (0-100)')),
                ('aprobado', models.BooleanField(default=False, verbose_name='¿Aprobó?')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='OpcionRespuesta',
        ),
    ]
